### ISSUE TITLE
Setup IMU

### ISSUE THREAD

**Issue by 4ndr3w** [Pitt-RAS/magellan-2018#21]
The onboard Teensy is connected to a BNO055 IMU. This IMU supports onboard filtering of orientation from a gyro and accelerometer. Optionally, it can also fuse a compass for an Earth oriented heading.

We need to publish this orientation as an IMU message in ROS. Since the IMU is on the Teensy, we will need to publish this from the Teensy code over rosserial.

Prior art is available at https://github.com/Pitt-RAS/Sailbot_ROS/blob/master/src/control_arduino/firmware/sailbot_controller/IMU.cpp

Since we'll be focusing mainly on running inside to start, we can run this sensor in IMUPLUS mode for now. This only fuses the gyro and accelerometer for an orientation that is relative to our starting orientation.

More information about this sensor is available here:
https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/overview

More information about the operation modes of this sensor is available here:
https://cdn-shop.adafruit.com/datasheets/BST_BNO055_DS000_12.pdf (page 20)

**Comment by xinkecf35** [comment]
Do I also need to add code for the appropriate files to subscribe to the published messages?

**Comment by 4ndr3w** [comment]
Nope, there's nothing setup yet that uses this data
